import { Component } from '@angular/core';

@Component({
  selector: 'app-services-modules',
  imports: [],
  templateUrl: './services-modules.component.html',
  styleUrl: './services-modules.component.scss'
})
export class ServicesModulesComponent {
  panels = [
    { title: 'Introduction to AI and Engineering', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'AI and AR/VR', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'AI and Coding skills', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'AI and Humanoid Robotics', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'AI in smart Transportation', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'Industry 4.0 and AI in Manufacturing', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'AI in IOT', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'AI and Projected Reality', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'AI in Esports and Game Development', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
    { title: 'Capstone project: AI Intergration', content: 'Real-world skill application through live projects, problem-solving tasks, and innovation challenges in a simulated professional environment. Workshops, seminars, networking events, and guest lectures for additional learning and industry trend exposure. Collaborative activities like team projects, group discussions, and peer-learning exercises to foster teamwork and innovation. Foundational knowledge and technical training for each technology field to ensure industry readiness.', isOpen: false },
  ];

  togglePanel(index: number) {
    this.panels[index].isOpen = !this.panels[index].isOpen;
  }
}
